[package]
name = "furaffinity-rs"
version = "0.1.0"
authors = ["Syfaro <syfaro@huefox.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.4"
scraper = "0.11"
regex = "1.3"
reqwest = "0.10.1"
image = "0.22"
chrono = "0.4"
img_hash = "3.0.0"

[dev-dependencies]
tokio = { version = "0.2", features = ["macros"] }
